# Setup
name:         Download and Install kaicoin
tagline:      Versatile, second generation cryptocurrency.
baseurl:      ""
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
